### ISSUE TITLE
Campo meli_category no existe en Productos

### ISSUE THREAD

**Issue by celm1990** [ctmil/payment_mercadopago#9]
Hola
Al realizar un pago en el website, se llega a esta [linea de codigo](https://github.com/ctmil/payment_mercadopago/blob/odoo10/models/mercadopago.py#L181) introducido en [este commit](https://github.com/ctmil/payment_mercadopago/commit/b2a7beccd94ab07aa97a9a4f724d32be8ef92d32), pero el campo referenciado ahi no existe en productos, es unnuevo campo pero donde se crea ese campo???. Falta algun modulo??.

Esto es en la rama 10, en la rama master no existen esos commits y por ende no existe el error.

**Comment by regaby** [comment]
Hola @celm1990 
Estoy teniendo este problema, como lo resolviste?

**Comment by celm1990** [comment]
Hola, cree un fork de este repo el cual esta aca https://github.com/laotraopcion/meli_oerp pero es una rama especifica para Chile, pero en este repo original no se si lo abran corregido.

**Comment by regaby** [comment]
Justamente faltaba la dependencia al módulo melo_oerp. Ahora voy a hacer un PR
